export interface VotesModel {
  blockCode: number | null;
  constituencyName: string;
  moza: string;
  dehya: string;
  city: string;
  patwarHalka: string;
  tapaydar: string;
  tehseel: string;
  talka: string;
  district: string;
  unionCouncil: string;
  bookNo: string;
  constituency: string;
  gender: string;
  voteSNo: number | null;
  familyNo: number | null;
  name: string;
  maritalStatus: string;
  fatherHusbandName: string;
  cnic: string;
  age: number | null;
  houseNo: string;
  street: string;
  phase: string;
  sector: string;
  lane: string;
  boulevardAvenue: string;
  otherArea: string;
}
