import { VotesModel } from "../interfaces/VotesModel";

export const dataEntryFormInitial: VotesModel = {
  blockCode: null,
  constituencyName: "",
  moza: "",
  dehya: "",
  city: "",
  patwarHalka: "",
  tapaydar: "",
  tehseel: "",
  talka: "",
  district: "",
  unionCouncil: "",
  bookNo: "",
  constituency: "",
  gender: "",
  voteSNo: null,
  familyNo: null,
  name: "",
  maritalStatus: "",
  fatherHusbandName: "",
  cnic: "",
  age: null,
  houseNo: "",
  street: "",
  phase: "",
  sector: "",
  lane: "",
  boulevardAvenue: "",
  otherArea: "",
};
