import { getData } from './helpers/getData';
import { uploadData } from './helpers/uploadData';
import { deleteData } from './helpers/deleteData';
import { updateVoteData } from './helpers/updateVoteData';
import { getPages } from './helpers/getPages';

export const authorized = {
  getData,
  uploadData,
  deleteData,
  updateVoteData,
  getPages,
};

export const getAuthorizedVoteFields = (req) => {
  const {
    blockCode,
    voteSNo,
    familyNo,
    gender,
    name,
    fatherHusbandName,
    maritalStatus,
    cnic,
    age,
    houseNo,
    street,
    phase,
    sector,
    lane,
    boulevardAvenue,
    otherArea,
    constituencyName,
    moza,
    dehya,
    city,
    patwarHalka,
    tapaydar,
    tehseel,
    talka,
    district,
    unionCouncil,
    bookNo,
    constituency,
    address,
    status,
    enteredBy,
    verifiedBy,
    createdAt,
  } = req.body;
  return {
    blockCode,
    voteSNo,
    familyNo,
    gender,
    name,
    fatherHusbandName,
    maritalStatus,
    cnic,
    age,
    houseNo,
    street,
    phase,
    sector,
    lane,
    boulevardAvenue,
    otherArea,
    constituencyName,
    moza,
    dehya,
    city,
    patwarHalka,
    tapaydar,
    tehseel,
    talka,
    district,
    unionCouncil,
    bookNo,
    constituency,
    address,
    status,
    enteredBy,
    verifiedBy,
    createdAt,
  };
};

export const getAuthorizedVoteTypes = () => {
  const voteTypes = {
    blockCode: 'required|integer',
    voteSNo: 'required|integer',
    familyNo: 'required|integer',
    name: 'required|string',
    gender: 'required|string',
    fatherHusbandName: 'required|string',
    maritalStatus: 'required|string',
    cnic: 'required|string',
    age: 'required|integer',
    houseNo: 'required|string',
    street: 'required|string',
    phase: 'required|string',
    sector: 'required|string',
    lane: 'required|string',
    boulevardAvenue: 'required|string',
    otherArea: 'required|string',
    constituencyName: 'required|string',
    moza: 'required|string',
    dehya: 'required|string',
    city: 'required|string',
    patwarHalka: 'required|string',
    tapaydar: 'required|string',
    tehseel: 'required|string',
    talka: 'required|string',
    district: 'required|string',
    unionCouncil: 'required|string',
    bookNo: 'required|string',
    constituency: 'required|string',
    // status: 'required|string',
    // address: 'required|string',
    // enteredBy: 'required',
    // verifiedBy: 'required',
    // createdAt: 'required|string',
  };
  return voteTypes;
};
